export const FETCH_PHONES_START = 'FETCH_PHONES_START';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_ERROR = 'FETCH_PHONES_ERROR';

export const MORE_PHONES_START = 'MORE_PHONES_START';
export const MORE_PHONES_SUCCESS = 'MORE_PHONES_SUCCESS';
export const MORE_PHONES_ERROR = 'MORE_PHONES_ERROR';

export const GET_PHONE_BY_ID_START = 'GET_PHONE_BY_ID_START';
export const GET_PHONE_BY_ID_SUCCESS = 'GET_PHONE_BY_ID_SUCCESS';
export const GET_PHONE_BY_ID_ERROR = 'GET_PHONE_BY_ID_ERROR';

export const ADD_PHONE_TO_BUSKET = 'ADD_PHONE_TO_BUSKET';

export const REMOVE_PHONE = 'REMOVE_PHONE';

export const FOUNDED_PHONES_SUCCESS = 'FOUNDED_PHONES_SUCCESS';
export const FOUNDED_PHONES_START = 'FOUNDED_PHONES_START';
export const FOUNDED_PHONES_ERROR = 'FOUNDED_PHONES_ERROR';

export const GET_CATEGORIES_PHONES_SUCCESS = 'GET_CATEGORIES_PHONES_SUCCESS';
export const GET_CATEGORIES_PHONES_START = 'GET_CATEGORIES_PHONES_START';
export const GET_CATEGORIES_PHONES_ERROR = 'GET_CATEGORIES_PHONES_ERROR';

export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY';

export const CLEAN_BUSKET = 'CLEAN_BUSKET';

export const DELETE_PHONE_FROM_BUSKET = 'DELETE_PHONE_FROM_BUSKET';